export default {
    LOAD_POKEMONS_SUCCESS: 'LOAD_POKEMONS_SUCCESS',
    LOAD_POKEMONS_FAILURE: 'LOAD_POKEMONS_FAILURE',
    LOAD_TYPES_SUCCESS: 'LOAD_TYPES_SUCCESS',
    LOAD_TYPES_FAILURE: 'LOAD_TYPES_FAILURE'
}
