export default {
    LOAD_POKELIST_SUCCESS: 'LOAD_POKELIST_SUCCESS',
    LOAD_POKELIST_FAILURE: 'LOAD_POKELIST_FAILURE',
    LOAD_POKEITEM_SUCCESS: 'LOAD_POKELIST_SUCCESS',
    LOAD_POKEITEM_FAILURE: 'LOAD_POKELIST_FAILURE',

    LOAD_TYPES_SUCCESS: 'LOAD_TYPES_SUCCESS',
    LOAD_TYPES_FAILURE: 'LOAD_TYPES_FAILURE'
}
